version: '3.1'

services:
  app:
    build: .
    container_name: app
    depends_on:
      - mongo
    ports:
      - '3000:3000'
      - '5454:5555'
    command: sh -c "node .output/server/index.mjs"
    environment:
      - DATABASE_URL=mongodb://root:prisma@mongo:27017/my-nuxt-app?authSource=admin

  mongo:
    build: ./mongodb_replica
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: prisma
      MONGO_REPLICA_HOST: mongo
      MONGO_REPLICA_PORT: 27017
    ports:
      - '27017:27017'

  nginx:
    image: nginx:1.21-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app